 version: '3'

 services:

  case-notebook-v1:
   image: datasci4health/case-notebook:v1

   container_name: case-notebook-v1
   restart: always
   ports:
     - 8081:80
     - 8881:8888  
   environment:  
     - CASE_NOTEBOOK_SERVICE_URL=http://localhost:8888

